AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 300

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false